/* tslint:disable */
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

/**
 * Base General Category schema
 */
export interface CategoryBaseSchema {
  Category?: CategoryBase;
  CategoryParamId?: CategoryParamId;
  CategoryPostBody?: CategoryPostBody;
  CategoryUpdateBody?: CategoryUpdateBody;
  CategoryDeleteBody?: CategoryDeleteBody;
  [k: string]: unknown;
}
export interface CategoryBase {
  id?: number;
  name?: string;
  created_at?: string;
  updated_at?: string;
  productsIDs?: string[];
}
export interface CategoryParamId {
  categoryID: string;
}
export interface CategoryPostBody {
  name: string;
}
export interface CategoryUpdateBody {
  id: number;
  name?: string;
}
export interface CategoryDeleteBody {
  id: number;
}
