/* tslint:disable */
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

export type CategoryPostBodySchema = BaseCategorySchema;

/**
 * Base Category schema
 */
export interface BaseCategorySchema {
  id?: string;
  name: string;
  created_at?: string;
  updated_at?: string;
  productsIDs?: string[];
}
